---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Finvolv Devpage"
subtitle: "Wellcome home"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: false
footer: '<p>Costomized by <a href="https://prajwalrajup.in">Prajwal Raju P</a> // Origian source <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "👋 Hi FinVolvers!"
  content: "This is a homepage for all the resource link"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  - name: "Home"
    icon: "fas fa-home"
    url: "#"
  - name: "Develop page!"
    icon: "fas fa-file-alt"
    url: "#develop-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Dev Env"
    icon: "fas fa-cloud"
    items:       
      - name: "IB Dashboard"
        logo: "assets/tools/sample.png"
        subtitle: "Dev Dashbaord for IB"
        keywords: "devIB IB IBdashboard Dashbaord"
        url: "https://dev-ib.getlend.in"
        target: "_blank"
      
      - name: "IB swagger"
        subtitle: "Dev swagger for IB"
        keywords: "IBSwagger swagger"
        logo: "https://seeklogo.com/images/S/swagger-logo-A49F73BAF4-seeklogo.com.png"
        url: "https://ib-dev-backend.getlend.in/ib/swagger-ui/index.html"
        target: "_blank"

  - name: "Tools"
    icon: "fa-solid fa-screwdriver-wrench"
    items:
      - name: "Repositories"
        keywords: "repo bitbucket git"
        logo: "https://www.axonius.com/hubfs/Adapter%20Logos/bitbucket%20logo.png"
        url: "https://bitbucket.org/kulizadev/workspace/overview/"
        target: "_blank"
